### PR TITLE
Create codeql.yml

### PR DESCRIPTION
**Pull request by swapnil-bhasale-td**
Configure CodeQL scanning.

### CODE REVIEW

**Comment by swapnil-bhasale-td** [comment]
@treasure-data/integrations need some assistance with java build steps for CodeQL. Thank you.

**Comment by imnutz** [comment]
@swapnil-bhasale-td I updated the builds. The Java build works now.

**Comment by swapnil-bhasale-td** [comment]
Thanks @imnutz, may a request a PR review as well. Thanks.

**Review by imnutz — APPROVED** [review]

**Review by nmpennypacker — APPROVED** [review]
Reviewed for data exfiltrations

**Pull request merged**
